### ISSUE TITLE
Unable to apply large k8s manifests with `kubernetes.core.k8s`

### ISSUE THREAD

**Issue by aussielunix** [ansible-collections/kubernetes.core#584]
##### SUMMARY

Unable to apply large k8s manifests with `kubernetes.core.k8s`

`Too long: must have at most 262144 bytes`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```
ansible [core 2.14.2]
  config file = /home/work/foo/ansible.cfg
  configured module search path = ['/home/work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/work/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/work/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/work/.local/bin/ansible
  python version = 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/work/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.5.1  
community.crypto  2.10.0 
community.general 6.3.0  
kubernetes.core   2.4.0  
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/work/foo/ansible.cfg
DEFAULT_HOST_LIST(/home/work/foo/ansible.cfg) = ['/home/work/foo/inventories/dev']
DEFAULT_REMOTE_USER(/home/work/foo/ansible.cfg) = lunix
HOST_KEY_CHECKING(/home/work/foo/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven
```

##### STEPS TO REPRODUCE

Try to apply a large manifest to a k8s cluster. 

```yaml
- name: Deploy canal operator
  kubernetes.core.k8s:
    src: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml"
    kubeconfig: "{{ kubeconfig_dir }}/admin.kubeconfig"
    apply: true
```

The same error occurs if you fetch the remote yaml and try to apply it from a registered variable.  
It is worth noting that this same error occurs when using `kubectl apply` but does not when using `kubectl create`

##### EXPECTED RESULTS

Manifest to be deployed without error

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"CustomResourceDefinition.apiextensions.k8s.io \\\\\"installations.operator.tigera.io\\\\\" is invalid: metadata.annotations: Too long: must have at most 262144 bytes\",\"reason\":\"Invalid\",\"details\":{\"name\":\"installations.operator.tigera.io\",\"group\":\"apiextensions.k8s.io\",\"kind\":\"CustomResourceDefinition\",\"causes\":[{\"reason\":\"FieldValueTooLong\",\"message\":\"Too long: must have at most 262144 bytes\",\"field\":\"metadata.annotations\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity"}

```

**Comment by gravesm** [comment]
@aussielunix This is a limitation of kubernetes and there's nothing we can do about it from our side. As you noted, the same problem happens when using kubectl. The reason it only fails when using `apply` and not `create` is because `apply` stores the last applied configuration for the resource in the `annotations` field. The resource is essentially twice the size. Using `create` would also fail with a sufficiently large resource.

Your best option here will be to use [server-side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/), which is implemented in kubernetes.core [here](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#parameter-server_side_apply). In addition to being a better form of apply, SSA does not store a second copy of the definition in the annotations.

I'm going to close this as there's nothing we can do here.
